### ISSUE TITLE
Installation Configuration

### ISSUE THREAD

**Issue by davidstoker** [trbs/sentry-auth-crowd#1]
Hello, thank you for creating this plugin for Sentry. I just wanted to leave a note that I had to set the following in my `sentry.conf.py` in addition to the other config variables in order to get this plugin to load and work. It would be helpful to add this to the Readme.

I'm currently running Sentry 8.17.0:

```
AUTHENTICATION_BACKENDS = (
    'sentry_auth_crowd.backend.SentryCrowdBackend',
)
```

These are the default settings in a fresh Sentry:

```
AUTHENTICATION_BACKENDS = (
    'sentry.utils.auth.EmailAuthBackend',
    # TODO(dcramer): we can't remove these until we rewrite more of social auth
    'social_auth.backends.github.GithubBackend',
    'social_auth.backends.bitbucket.BitbucketBackend',
    'social_auth.backends.trello.TrelloBackend',
    'social_auth.backends.asana.AsanaBackend',
)
```

**Comment by trbs** [comment]
Thanks and your welcome :)

Would you mind submitting a PR to update the README ?
