### ISSUE TITLE
Doesn't work with Sentry 21.10.0

### ISSUE THREAD

**Issue by kurtruk** [trbs/sentry-auth-crowd#4]
Hi. 

It's doesn't work with Sentry 21.10.0

I configured clean instance Sentry with docker, add sentry-auth-crowd in requirements.txt and other setting in sentry.conf.py. In admin area sentry in Environment  section I see Crowd in AUTHENTICATION_BACKENDS and sentry-auth-crowd in Modules section. But when try to login got error: _Please enter a correct username and password. Note that both fields may be case-sensitive._

Could you please check it?

**Comment by trbs** [comment]
I have not been using _sentry-auth-crowd_ for awhile now.
So unless anybody is willing to sponsor 💵 work on it please consider it a stale / abandoned project 😄

**Comment by kurtruk** [comment]
What if I sponsor a fix for working with new version of Sentry?
It's very important for me :)

**Comment by trbs** [comment]
If you want to create a PR, I am happy to merge it and create a new release 👍
